spring.application.name=Topic4
# Địa chỉ tới Database (thay ten_database bằng tên db bạn đã tạo trong pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/SWP391_SealHackathon

# Tài khoản mặc định của PostgreSQL thường là postgres
spring.datasource.username=postgres

# Mật khẩu lúc bạn cài đặt PostgreSQL
spring.datasource.password=12345

# Tự động cập nhật bảng trong DB khi code thay đổi
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect