package vn.edu.fpt.seal.modules.incident.service;

import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import vn.edu.fpt.seal.common.enums.*; import vn.edu.fpt.seal.common.exception.ApiException; import vn.edu.fpt.seal.modules.event.repository.EventRepository; import vn.edu.fpt.seal.modules.incident.dto.*; import vn.edu.fpt.seal.modules.incident.entity.*; import vn.edu.fpt.seal.modules.incident.mapper.IncidentMapper; import vn.edu.fpt.seal.modules.incident.repository.*; import vn.edu.fpt.seal.modules.round.repository.RoundRepository; import vn.edu.fpt.seal.modules.submission.repository.SubmissionRepository; import vn.edu.fpt.seal.modules.team.repository.TeamRepository; import vn.edu.fpt.seal.modules.track.repository.TrackRepository; import vn.edu.fpt.seal.modules.user.entity.User; import vn.edu.fpt.seal.modules.user.repository.UserRepository; import vn.edu.fpt.seal.security.CurrentUser;
import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor
public class IncidentService {
 private final IncidentReportRepository reportRepo; private final IncidentEvidenceRepository evidenceRepo; private final IncidentActionRepository actionRepo; private final EventRepository eventRepo; private final TrackRepository trackRepo; private final RoundRepository roundRepo; private final TeamRepository teamRepo; private final SubmissionRepository submissionRepo; private final UserRepository userRepo;
 @Transactional(readOnly=true) public Page<IncidentResponse> list(UUID eventId, UUID reporterId, IncidentStatus status, Pageable p){ Page<IncidentReport> page = eventId!=null?reportRepo.findByEventId(eventId,p): reporterId!=null?reportRepo.findByReporterId(reporterId,p): status!=null?reportRepo.findByStatus(status,p): reportRepo.findAll(p); return page.map(this::toResponse); }
 @Transactional(readOnly=true) public IncidentResponse get(UUID id){return toResponse(find(id));}
 @Transactional public IncidentResponse create(CreateIncidentRequest req, Authentication auth){ User reporter=currentUser(auth); IncidentReport i=IncidentReport.builder().event(eventRepo.findById(req.eventId()).orElseThrow(()->ApiException.notFound("Event not found: "+req.eventId()))).track(req.trackId()==null?null:trackRepo.findById(req.trackId()).orElseThrow(()->ApiException.notFound("Track not found: "+req.trackId()))).round(req.roundId()==null?null:roundRepo.findById(req.roundId()).orElseThrow(()->ApiException.notFound("Round not found: "+req.roundId()))).team(req.teamId()==null?null:teamRepo.findById(req.teamId()).orElseThrow(()->ApiException.notFound("Team not found: "+req.teamId()))).submission(req.submissionId()==null?null:submissionRepo.findById(req.submissionId()).orElseThrow(()->ApiException.notFound("Submission not found: "+req.submissionId()))).reporter(reporter).type(req.type()).status(IncidentStatus.reported).severity(trim(req.severity())).category(trim(req.category())).title(req.title().trim()).description(req.description().trim()).build(); return toResponse(reportRepo.save(i)); }
 @Transactional public IncidentResponse updateStatus(UUID id, UpdateIncidentStatusRequest req, Authentication auth){ IncidentReport i=find(id); IncidentStatus old=i.getStatus(); i.setStatus(req.status()); if(req.assignedCoordinatorId()!=null)i.setAssignedCoordinator(userRepo.findById(req.assignedCoordinatorId()).orElseThrow(()->ApiException.notFound("Coordinator not found: "+req.assignedCoordinatorId()))); if(req.status()==IncidentStatus.resolved||req.status()==IncidentStatus.rejected)i.setResolvedAt(LocalDateTime.now()); actionRepo.save(IncidentAction.builder().incident(i).actionBy(currentUser(auth)).actionType(req.status()==IncidentStatus.rejected?IncidentActionType.reject_report:IncidentActionType.other).oldValue(old.name()).newValue(req.status().name()).note(req.note()).build()); return toResponse(i); }
 @Transactional public IncidentResponse addEvidence(UUID id, AddIncidentEvidenceRequest req, Authentication auth){ IncidentReport i=find(id); if((req.fileUrl()==null||req.fileUrl().isBlank())&&(req.externalUrl()==null||req.externalUrl().isBlank())) throw ApiException.badRequest("Either fileUrl or externalUrl is required"); evidenceRepo.save(IncidentEvidence.builder().incident(i).uploadedBy(currentUser(auth)).fileUrl(trim(req.fileUrl())).externalUrl(trim(req.externalUrl())).description(trim(req.description())).build()); return toResponse(i); }
 @Transactional public IncidentResponse addAction(UUID id, AddIncidentActionRequest req, Authentication auth){ IncidentReport i=find(id); actionRepo.save(IncidentAction.builder().incident(i).actionBy(currentUser(auth)).actionType(req.actionType()).targetType(trim(req.targetType())).targetId(req.targetId()).oldValue(trim(req.oldValue())).newValue(trim(req.newValue())).note(trim(req.note())).build()); return toResponse(i); }
 private IncidentReport find(UUID id){return reportRepo.findWithRelationsById(id).orElseThrow(()->ApiException.notFound("Incident not found: "+id));}
 private IncidentResponse toResponse(IncidentReport i){return IncidentMapper.toResponse(i,evidenceRepo.findByIncidentIdOrderByCreatedAtAsc(i.getId()),actionRepo.findByIncidentIdOrderByCreatedAtAsc(i.getId()));}
 private User currentUser(Authentication auth){ if(auth==null||!(auth.getPrincipal() instanceof CurrentUser c)) throw ApiException.forbidden("Authentication required"); return userRepo.findById(c.getId()).orElseThrow(()->ApiException.notFound("User not found: "+c.getId())); }
 private String trim(String s){return s==null?null:s.trim();}
}
