package vn.edu.fpt.seal.common.enums;

public enum AuditAction {
    CREATE, UPDATE, DELETE,
    APPROVE_USER, REJECT_USER,
    SUBMIT_PROJECT, SCORE_SUBMISSION, UPDATE_SCORE,
    DISQUALIFY_TEAM, PROMOTE_TEAM, ELIMINATE_TEAM,
    CREATE_INCIDENT, PROCESS_INCIDENT, RESOLVE_INCIDENT, REJECT_INCIDENT
}
